version: '3.3'

services:
  api_1:
    build: ./Api_1
    ports:
      - "8081:80"
    restart: always
  api_2:
    build: ./Api_2
    ports:
      - "8082:80"
    restart: always
  ocelot_gateway:
    build: ./Ocelot_Gateway
    ports:
      - "8083:80"
    restart: always